version: "3.9"

services:
  db:
    image: postgres:15-alpine
    container_name: tiss_db
    restart: always
    environment:
      POSTGRES_USER: tiss_user
      POSTGRES_PASSWORD: tiss_password
      POSTGRES_DB: tiss
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tiss_backend
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://tiss_user:tiss_password@db:5432/tiss
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  postgres_data:
