version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: tiss_db
    restart: always
    environment:
      POSTGRES_USER: tiss_user
      POSTGRES_PASSWORD: tiss_password
      POSTGRES_DB: tiss
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tiss_user -d tiss"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tiss_backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://tiss_user:tiss_password@db:5432/tiss
      PYTHONPATH: /app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  postgres_data:
